version: '3.7'

services:

  oracle-xe:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - oracle-volume:/opt/oracle/oradata
    container_name: django_bootstrap5_oracle-xe

  django:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - oracle-xe
    container_name: django_bootstrap5

volumes:
  oracle-volume: